"""add_user_preferences

Revision ID: 647aee90bb3f
Revises: 3c5c7196db38
Create Date: 2026-01-11 10:23:49.300156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '647aee90bb3f'
down_revision: Union[str, None] = '3c5c7196db38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type first
    thememode = sa.Enum('LIGHT', 'DARK', 'SYSTEM', name='thememode')
    thememode.create(op.get_bind(), checkfirst=True)

    # Add columns with server defaults for existing rows
    op.add_column('users', sa.Column('theme', thememode, nullable=False, server_default='SYSTEM'))
    op.add_column('users', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default='TWD'))
    op.add_column('users', sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default='zh-TW'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
